// The helper attribute on the field is
// generated by another proc macro
//
// #[skip_serializing_none] adds #[serde(skip_serializing_if = "Option::is_none")]
// to fields that are `Option`s
//
// NOTE: the #[skip_serializing_none] needs to be
// placed before the `#[derive(Serialize)]`
#![allow(unused)]

mod derive_alias {
    derive_aliases::define! {
        Serialize = ::serde::Serialize;
        Clone = ::core::clone::Clone;
    }
}

#[serde_with::skip_serializing_none]
#[derive_aliases::derive(..Clone)]
#[derive_aliases::derive(..Serialize)]
struct A {
    field: Option<()>,
}

#[serde_with::skip_serializing_none]
#[derive(::core::clone::Clone)]
#[derive_aliases::derive(..Serialize)]
struct A2 {
    field: Option<()>,
}

#[derive_aliases::derive(..Clone)]
#[serde_with::skip_serializing_none]
#[derive_aliases::derive(..Serialize)]
struct B {
    field: Option<()>,
}

#[derive_aliases::derive(..Clone)]
#[serde_with::skip_serializing_none]
#[derive(::serde::Serialize)]
struct B2 {
    field: Option<()>,
}
