//! The helper attribute on the field is
//! generated by another proc macro
//!
//! #[skip_serializing_none] adds #[serde(skip_serializing_if = "Option::is_none")]
//! to fields that are `Option`s
//!
//! NOTE: the #[skip_serializing_none] needs to be
//! placed before the `#[derive(Serialize)]`
#![allow(unused)]

use core::prelude::v1::derive as std_derive;
use derive_aliases::derive;

mod derive_alias {
    derive_aliases::define! {
        Serialize = ::serde::Serialize;
        Clone = ::core::clone::Clone;
    }
}

#[serde_with::skip_serializing_none]
#[derive(..Clone)]
#[derive(..Serialize)]
/*^
@(all(), $(::serde::Serialize))
@(all(), $(::core::clone::Clone))
*/
struct A {
    field: Option<()>,
}

#[serde_with::skip_serializing_none]
#[std_derive(::core::clone::Clone)]
#[derive(..Serialize)]
/*^
@(all(), $(::serde::Serialize))
*/
struct A2 {
    field: Option<()>,
}

#[derive(..Clone)]
#[serde_with::skip_serializing_none]
#[derive(..Serialize)]
/*^
@(all(), $(::serde::Serialize))
@(all(), $(::core::clone::Clone))
serde_with::skip_serializing_none
*/
struct B {
    field: Option<()>,
}

#[derive(Clone)]
#[serde_with::skip_serializing_none]
#[std_derive(::serde::Serialize)]
/*^
@(all(), $(::serde::Serialize))
@(all(), $(::core::clone::Clone))
serde_with::skip_serializing_none
*/
struct BM {
    field: Option<()>,
}

mod b {
    use super::*;

    #[derive_aliases::derive(..Clone)]
    #[serde_with::skip_serializing_none]
    #[std_derive(::serde::Serialize)]
    /*^
    @(all(), $(::serde::Serialize))
    @(all(), $(::core::clone::Clone))
    serde_with::skip_serializing_none
    */
    struct B2 {
        field: Option<()>,
    }
}

// #[test]
// fn must() {
//     let s = serde_json::to_string(&B { field: None }).unwrap();

//     panic!("{s}");
// }
