//! Documentation for Derive Aliases @generated by the `derive_aliases` crate
//! 
//! Derive aliases are defined in `derive_aliases.rs`
#![allow(warnings)]
#![doc(hidden)]

/// Derive alias `..Copy` expands to the following derives:
///
/// - [`Copy`]
/// - [`Clone`]
pub trait Copy {}

/// Derive alias `..Eq` expands to the following derives:
///
/// - [`PartialEq`]
/// - [`Eq`]
pub trait Eq {}

/// Derive alias `..Ord` expands to the following derives:
///
/// - [`PartialOrd`]
/// - [`Ord`]
/// - [`PartialEq`]
/// - [`Eq`]
pub trait Ord {}

/// Derive alias `..Together` expands to the following derives:
///
/// - [`PartialOrd`]
/// - [`std::hash::Hash`]
pub trait Together {}
